#!/usr/bin/ bash

mkdir -p ~/.ssh
if [ ! -f ~/.dotfiles/ssh/id_rsa ]; then
  ansible-vault decrypt ~/.dotfiles/ssh/id_rsa --output ~/.ssh/id_rsa
  cp ~/.dotfiles/ssh/id_rsa.pub ~/.ssh/id_rsa.pub
  chmod 600 ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa.pub
else
  echo "SSH key already exists. Skipping..."
fi
