---
- name: Check if Neovim is installed
  ansible.builtin.command: nvim --version
  register: neovim_check
  ignore_errors: true
  changed_when: false

- name: Dependencies
  ansible.builtin.package:
    name:
      - ninja-build
      - gettext
      - cmake
      - g++
      - unzip
      - curl
      - git
    state: present
  become: true
  when: neovim_check.failed  # Only run if Neovim is not installed

- name: Clone
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "~/neovim"
    force: true
    repo: https://github.com/neovim/neovim.git
    single_branch: true
    update: true
    version: "{{ neovim_version | default('master') }}"
  register: clone
  when: neovim_check.failed  # Only clone if Neovim is not installed

- name: Build
  make: # noqa no-handler
    chdir: "~/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

- name: Install
  make: # noqa no-handler
    chdir: "~/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  tags:
    - install
  become: true
  when: clone.changed

- name: Remove build folder
  ansible.builtin.file:
    path: "~/neovim/build"
    state: absent
  become: true
