---

- name: Check if Neovim is installed
  command: nvim --version
  register: neovim_check
  ignore_errors: yes

- name: Install dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - g++
      - unzip
      - curl
      - git
    state: present
  when: neovim_check.rc != 0

- name: Clone Neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /usr/local/src/neovim
    version: stable
  when: neovim_check.rc != 0

- name: Build Neovim
  command: make CMAKE_BUILD_TYPE=RelWithDebInfo
  args:
    chdir: /usr/local/src/neovim
  when: neovim_check.rc != 0

- name: Install Neovim
  command: sudo make install
  args:
    chdir: /usr/local/src/neovim
  when: neovim_check.rc != 0

- name: Verify Neovim Installation
  command: nvim --version
  register: neovim_final_check
  changed_when: false

- name: Display Neovim Version
  debug:
    msg: "{{ neovim_final_check.stdout_lines }}"
