---
- name: Check if Rust is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  register: rustc_stat

- name: Install Rust via rustup
  ansible.builtin.shell: >
    curl --proto '=https' --tlsv1.2 -sSf {{ rustup_script_url }} | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  when: not rustc_stat.exists
