---
- name: Bootstrap Development Environment
  hosts: localhost
  gather_facts: true
  become: true

  vars_prompt:
    - name: default_zsh
      prompt: "Do you want to make Zsh the default shell ([y]/n)"
      private: false
      default: y
    - name: install_zsh
      prompt: "Do you want to install Oh-My-Zsh? ([y]/n)"
      private: false
      default: y
    - name: install_nodejs
      prompt: "Do you want to install Node.js? ([y]/n)"
      private: false
      default: y
    - name: install_tmux
      prompt: "Do you want to install Tmux (Oh-My-Tmux)? ([y]/n)"
      private: false
      default: y
    - name: install_docker
      prompt: "Do you want to install Docker? (y/[n])"
      private: false
      default: n
    - name: install_r
      prompt: "Do you want to install R? (y/[n])"
      private: false
      default: n
    - name: install_go
      prompt: "Do you want to install Go? (y/[n])"
      private: false
      default: n
    - name: install_cargo
      prompt: "Do you want to install Cargo? (y/[n])"
      private: false
      default: n
    - name: install_k3s
      prompt: "Do you want to install K3s? (y/[n])"
      private: false
      default: n
    - name: install_conda
      prompt: "Do you want to install Conda? (y/[n])"
      private: false
      default: n
  tasks:
    - name: Install geerlingguy.docker
      community.general.ansible_galaxy_install:
        type: role
        name: "geerlingguy.docker"
        dest: "{{ ansible_user_dir }}/.ansible/roles"
        force: true
      when: install_docker == 'y'

    - name: Install geerlingguy.go
      community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.go
        dest: ~/.ansible/roles
        force: true
      when: install_go == 'y'

    - name: Install viasite-ansible.zsh
      community.general.ansible_galaxy_install:
        type: role
        name: viasite-ansible.zsh
        dest: "{{ ansible_user_dir }}/.ansible/roles"
        force: true
      when: install_zsh == 'y'

    - name: Install robertdebock.cargo
      community.general.ansible_galaxy_install:
        type: role
        name: robertdebock.cargo
        dest: "{{ ansible_user_dir }}/.ansible/roles"
        force: true
      when: install_cargo == 'y'

    - name: Install xanmanning.k3s
      community.general.ansible_galaxy_install:
        type: role
        name: xanmanning.k3s
        dest: "{{ ansible_user_dir }}/.ansible/roles"
        force: true
      when: install_k3s == 'y'

    - name: Install Oh-My-Zsh if user selected yes
      ansible.builtin.include_role:
        name: viasite-ansible.zsh
      vars:
        zsh_user: "{{ user_name }}"
        zsh_change_user_shell: true
      when: install_zsh == 'y'

    - name: Install Neovim
      ansible.builtin.include_role:
        name: neovim
      vars:
        neovim_user: "{{ user_name }}"

    - name: Apply WSL Clipboard Support if on WSL
      ansible.builtin.include_role:
        name: wsl_clipboard_support

    - name: Apply Node.js role
      ansible.builtin.include_role:
        name: nodejs
      vars:
        nodejs_user: "{{ user_name }}"
      when: install_nodejs == 'y'

    - name: Apply Tmux role
      ansible.builtin.include_role:
        name: tmux
      vars:
        tmux_user: "{{ user_name }}"
      when: install_tmux == 'y'

    - name: Apply Go role
      ansible.builtin.include_role:
        name: geerlingguy.go
      when: install_go == 'y'

    - name: Apply Cargo role
      ansible.builtin.include_role:
        name: robertdebock.cargo
      when: install_cargo == 'y'

    - name: Apply Docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      when: install_docker == 'y'

    - name: Apply K3s role
      ansible.builtin.include_role:
        name: xanmanning.k3s
      when: install_k3s == 'y'

    - name: Apply Conda role
      ansible.builtin.include_role:
        name: conda
      when: install_conda == 'y'

    - name: Apply R role
      ansible.builtin.include_role:
        name: r
      when: install_r == 'y'

    - name: Apply Stow role
      ansible.builtin.include_role:
        name: stow
