---
- name: Include Linux installation
  ansible.builtin.import_tasks: install_linux.yml
  when: ansible_system != "Windows"

- name: Include Windows installation
  ansible.builtin.import_tasks: install_windows.yml
  when: ansible_system == "Windows"
